"""Wrap Phase 3 combine / index / chat. Fine-tune stays CLI-only."""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

from ..corpus import collect_chunk_jsonl, count_jsonl_files
from ..jobs import Job, RUNNER
from ..models import ChatRequest, Phase3Request
from ..paths import Layout, require
from ..session import SESSION
from ..settings import jobs_dir, ollama_host, pg_dsn_set


def default_store(layout: Layout) -> Path:
    if layout.phase3:
        return layout.phase3 / "data" / "store" / "index"
    return layout.ui / "data" / "store" / "index"


def default_processed(layout: Layout) -> Path:
    if layout.phase3:
        return layout.phase3 / "data" / "processed"
    return layout.ui / "data" / "processed" / "phase3"


def _phase_outputs(layout: Layout, req: Phase3Request) -> list[Path]:
    roots: list[Path] = []
    if req.include_phase1 and layout.phase1:
        roots.append(layout.phase1 / "data" / "processed")
    if req.include_phase2 and layout.phase2:
        roots.append(layout.phase2 / "data" / "processed")
    extra = req.processed_dir
    if extra:
        roots.append(Path(extra).expanduser())
    return collect_chunk_jsonl(roots)


def start_phase3(layout: Layout, req: Phase3Request) -> Job:
    phase3 = require(layout.phase3, "Phase 3 (arkguru-rag-slm)")
    processed = Path(req.processed_dir or default_processed(layout)).expanduser()
    processed.mkdir(parents=True, exist_ok=True)
    store = Path(req.store or default_store(layout)).expanduser()
    store.parent.mkdir(parents=True, exist_ok=True)

    inputs = _phase_outputs(layout, req)
    if req.sink == "file" and not inputs:
        raise FileNotFoundError(
            "No Phase 1/2 JSONL chunks found. Run Phase 1 (and optionally "
            "Phase 2) first, or point processed_dir at existing chunks."
        )
    if req.sink == "postgres" and not pg_dsn_set():
        raise RuntimeError("Postgres sink requires PG_DSN in the environment.")

    job_dir = jobs_dir() / "phase3-pending"
    job_dir.mkdir(parents=True, exist_ok=True)
    runner_path = job_dir / "run_phase3.py"
    corpus = processed / "corpus.jsonl"
    runner_path.write_text(_cli_driver_source(), encoding="utf-8")

    cmd = [
        sys.executable,
        str(runner_path),
        "--python",
        sys.executable,
        "--sink",
        req.sink,
        "--embedder",
        req.embedder,
        "--model-name",
        req.model_name,
        "--dim",
        str(req.dim),
        "--store",
        str(store),
        "--corpus",
        str(corpus),
        "--out-train",
        str(processed / "train.jsonl"),
        "--skip-finetune",
        "1" if req.skip_finetune else "0",
    ]
    for path in inputs:
        cmd.extend(["--input", str(path)])

    def _result(_job: Job) -> dict[str, Any]:
        counts = count_jsonl_files(processed)
        store_jsonl = store.with_suffix(".jsonl")
        indexed = 0
        if store_jsonl.exists():
            indexed = sum(1 for line in store_jsonl.open() if line.strip())
        SESSION.sink = req.sink
        SESSION.embedder = req.embedder
        SESSION.store = str(store)
        SESSION.dim = req.dim
        return {
            "sink": req.sink,
            "embedder": req.embedder,
            "store": str(store),
            "corpus": str(corpus) if corpus.exists() else None,
            "inputs": [str(p) for p in inputs],
            "chunk_rows": counts["rows"],
            "indexed_rows": indexed,
            "skip_finetune": req.skip_finetune,
            "finetune": (
                "skipped — CLI only. From arkguru-rag-slm: make finetune"
                if req.skip_finetune
                else "requested (still CLI-only in this wizard)"
            ),
            "pg_dsn_set": pg_dsn_set(),
        }

    return RUNNER.start(
        "phase3",
        cmd,
        cwd=phase3,
        env={"PYTHONPATH": layout.pythonpath(phase3)},
        log_path=job_dir / "phase3.log",
        on_complete=_result,
    )


def _cli_driver_source() -> str:
    """One job: shell out to the existing Phase 3 CLIs (no pipeline rewrite)."""
    return r'''
"""Generated by arkguru-ui — subprocesses existing phase3_rag CLIs."""
from __future__ import annotations

import argparse
import subprocess
import sys


def _run(cmd: list[str]) -> None:
    print("[wizard]", " ".join(cmd), flush=True)
    subprocess.check_call(cmd)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--python", required=True)
    ap.add_argument("--sink", choices=["file", "postgres"], required=True)
    ap.add_argument("--embedder", required=True)
    ap.add_argument("--model-name", required=True)
    ap.add_argument("--dim", type=int, required=True)
    ap.add_argument("--store", required=True)
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--out-train", required=True)
    ap.add_argument("--skip-finetune", required=True)
    ap.add_argument("--input", action="append", default=[])
    args = ap.parse_args(argv)
    py = args.python

    if args.skip_finetune != "1":
        print("[wizard] Fine-tune is CLI-only (cd arkguru-rag-slm && make finetune); continuing with combine/index.", flush=True)
    else:
        print("[wizard] Fine-tune skipped (CLI-only: cd arkguru-rag-slm && make finetune)", flush=True)

    if args.sink == "postgres":
        print("[wizard] postgres path: python -m phase3_rag.embed_datastore", flush=True)
        _run([py, "-m", "phase3_rag.embed_datastore",
              "--embedder", args.embedder, "--model", args.model_name,
              "--dim", str(args.dim)])
        return 0

    if not args.input:
        print("[wizard] no input JSONL files", flush=True)
        return 2
    _run([py, "-m", "phase3_rag.prepare_dataset",
          "--inputs", *args.input,
          "--out-corpus", args.corpus,
          "--out-train", args.out_train,
          "--mode", "self_supervised"])
    _run([py, "-m", "phase3_rag.quickstart",
          "--add", args.corpus,
          "--embedder", args.embedder,
          "--model-name", args.model_name,
          "--store", args.store])
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _ollama_up() -> bool:
    try:
        import httpx

        r = httpx.get(f"{ollama_host()}/api/tags", timeout=2.0)
        return r.status_code < 500
    except Exception:
        return False


def chat(layout: Layout, req: ChatRequest) -> dict[str, Any]:
    phase3 = require(layout.phase3, "Phase 3 (arkguru-rag-slm)")
    if str(phase3) not in sys.path:
        sys.path.insert(0, str(phase3))
    if layout.common and str(layout.common) not in sys.path:
        sys.path.insert(0, str(layout.common))

    sink = req.sink or SESSION.sink or "file"
    embedder = req.embedder or SESSION.embedder or "hashing"
    store_path = Path(req.store or SESSION.store or default_store(layout))
    ollama = _ollama_up()
    model = req.model if (req.model and ollama) else None

    if sink == "postgres":
        answer, sources = _chat_postgres(req.question, embedder, req.dim, req.top_k, model)
        store_label = "postgres"
    else:
        answer, sources = _chat_file(
            req.question, embedder, store_path, req.top_k, model, req.dim
        )
        store_label = str(store_path)

    extractive = answer.strip().startswith("[extractive]") or not ollama or model is None
    return {
        "answer": answer,
        "sources": sources,
        "extractive": extractive,
        "ollama": ollama,
        "store": store_label,
        "embedder": embedder,
    }


def _chat_file(
    question: str,
    embedder: str,
    store_path: Path,
    top_k: int,
    model: str | None,
    dim: int,
) -> tuple[str, list[dict[str, Any]]]:
    from phase3_rag.embedder import Embedder
    from phase3_rag.vector_store import LocalVectorStore
    from phase3_rag import quickstart

    store = LocalVectorStore(str(store_path))
    if len(store) == 0:
        raise FileNotFoundError(
            f"Local vector store is empty at {store_path}. Run Phase 3 index first."
        )
    emb = Embedder(backend=embedder, dim=dim)
    hits = quickstart.retrieve(store, emb, question, top_k)
    answer = quickstart.answer(question, hits, model)
    return answer, [_source_from_hit(h) for h in hits]


def _chat_postgres(
    question: str,
    embedder: str,
    dim: int,
    top_k: int,
    model: str | None,
) -> tuple[str, list[dict[str, Any]]]:
    if not os.environ.get("PG_DSN"):
        raise RuntimeError("PG_DSN is not set")
    from common.datastore_config import open_chunk_store
    from phase3_rag.embedder import Embedder
    from phase3_rag import quickstart

    # Column order matches phase3_rag.run_pdfs._HIT (common.datastore search_*).
    cols = {
        "chunk_id": 0,
        "text": 1,
        "section": 2,
        "source_id": 3,
        "page": 4,
        "url": 5,
        "parent_id": 6,
        "chunk_index": 7,
        "title": 8,
        "lang": 9,
        "score": 10,
    }
    emb = Embedder(backend=embedder, dim=dim)
    store = open_chunk_store(dim=emb.dim)
    qvec = emb.encode([question])[0].tolist()
    rows = store.search_dense(qvec, k=top_k)
    hits: list[dict[str, Any]] = []
    for row in rows:
        hits.append(
            {
                "chunk_id": row[cols["chunk_id"]],
                "text": row[cols["text"]] or "",
                "section": row[cols["section"]],
                "source_id": row[cols["source_id"]],
                "page": row[cols["page"]],
                "url": row[cols["url"]],
                "parent_id": row[cols["parent_id"]],
                "chunk_index": row[cols["chunk_index"]],
            }
        )
    if not hits:
        return "No relevant context found.", []
    return quickstart.answer(question, hits, model), [_source_from_hit(h) for h in hits]


def _source_from_hit(hit: Any) -> dict[str, Any]:
    if isinstance(hit, dict):
        return {
            "chunk_id": hit.get("chunk_id"),
            "source_id": hit.get("source_id"),
            "page": hit.get("page"),
            "section": hit.get("section"),
            "url": hit.get("url"),
            "chunk_index": hit.get("chunk_index"),
            "text": (hit.get("text") or "")[:400],
        }
    return {
        "chunk_id": getattr(hit, "chunk_id", None),
        "source_id": getattr(hit, "source_id", None),
        "page": getattr(hit, "page", None),
        "section": getattr(hit, "section", None),
        "url": getattr(hit, "url", None),
        "chunk_index": getattr(hit, "chunk_index", None),
        "text": (getattr(hit, "text", "") or "")[:400],
    }
